-- Auto-generated by scripts/export_schema.py
-- Dialect: MySQL


CREATE TABLE backtest_results (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	strategy_id INTEGER NOT NULL COMMENT '策略ID', 
	symbol VARCHAR(50) NOT NULL COMMENT '交易对', 
	`interval` VARCHAR(10) NOT NULL COMMENT '时间周期', 
	start_time DATETIME NOT NULL COMMENT '回测开始时间', 
	end_time DATETIME NOT NULL COMMENT '回测结束时间', 
	initial_capital FLOAT NOT NULL COMMENT '初始资金', 
	final_capital FLOAT NOT NULL COMMENT '最终资金', 
	total_return FLOAT COMMENT '总收益率', 
	sharpe_ratio FLOAT COMMENT '夏普比率', 
	max_drawdown FLOAT COMMENT '最大回撤', 
	win_rate FLOAT COMMENT '胜率', 
	total_trades INTEGER COMMENT '总交易次数', 
	result_data TEXT COMMENT '详细结果(JSON)', 
	created_at DATETIME COMMENT '创建时间', 
	PRIMARY KEY (id)
)

;

CREATE INDEX idx_strategy_time ON backtest_results (strategy_id, start_time);


CREATE TABLE klines (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	exchange VARCHAR(50) NOT NULL COMMENT '交易所', 
	symbol VARCHAR(50) NOT NULL COMMENT '交易对', 
	`interval` VARCHAR(10) NOT NULL COMMENT '时间周期', 
	open_time DATETIME NOT NULL COMMENT '开盘时间', 
	open FLOAT NOT NULL COMMENT '开盘价', 
	high FLOAT NOT NULL COMMENT '最高价', 
	low FLOAT NOT NULL COMMENT '最低价', 
	close FLOAT NOT NULL COMMENT '收盘价', 
	volume FLOAT NOT NULL COMMENT '成交量', 
	close_time DATETIME NOT NULL COMMENT '收盘时间', 
	quote_volume FLOAT COMMENT '成交额', 
	trades INTEGER COMMENT '成交笔数', 
	created_at DATETIME COMMENT '创建时间', 
	PRIMARY KEY (id)
)

;

CREATE INDEX idx_symbol_interval_time ON klines (exchange, symbol, `interval`, open_time);


CREATE TABLE orders (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	exchange VARCHAR(50) NOT NULL COMMENT '交易所', 
	order_id VARCHAR(100) NOT NULL COMMENT '交易所订单ID', 
	symbol VARCHAR(50) NOT NULL COMMENT '交易对', 
	side VARCHAR(10) NOT NULL COMMENT '买卖方向: buy/sell', 
	type VARCHAR(20) NOT NULL COMMENT '订单类型: market/limit', 
	price FLOAT COMMENT '委托价格', 
	amount FLOAT NOT NULL COMMENT '委托数量', 
	filled FLOAT COMMENT '成交数量', 
	status VARCHAR(20) NOT NULL COMMENT '订单状态', 
	strategy_id INTEGER COMMENT '策略ID', 
	created_at DATETIME COMMENT '创建时间', 
	updated_at DATETIME COMMENT '更新时间', 
	PRIMARY KEY (id)
)

;

CREATE INDEX idx_exchange_order ON orders (exchange, order_id);

CREATE INDEX idx_strategy ON orders (strategy_id);


CREATE TABLE positions (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	exchange VARCHAR(50) NOT NULL COMMENT '交易所', 
	symbol VARCHAR(50) NOT NULL COMMENT '交易对', 
	side VARCHAR(10) NOT NULL COMMENT '持仓方向: long/short', 
	amount FLOAT NOT NULL COMMENT '持仓数量', 
	entry_price FLOAT NOT NULL COMMENT '开仓均价', 
	current_price FLOAT COMMENT '当前价格', 
	unrealized_pnl FLOAT COMMENT '未实现盈亏', 
	strategy_id INTEGER COMMENT '策略ID', 
	opened_at DATETIME COMMENT '开仓时间', 
	updated_at DATETIME COMMENT '更新时间', 
	closed_at DATETIME COMMENT '平仓时间', 
	PRIMARY KEY (id)
)

;

CREATE INDEX idx_exchange_symbol ON positions (exchange, symbol);


CREATE TABLE strategies (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(100) NOT NULL COMMENT '策略名称', 
	code VARCHAR(50) NOT NULL COMMENT '策略代码', 
	description TEXT COMMENT '策略描述', 
	parameters TEXT COMMENT '策略参数(JSON)', 
	enabled BOOL COMMENT '是否启用', 
	exchange VARCHAR(50) COMMENT '交易所', 
	symbol VARCHAR(50) COMMENT '交易对', 
	`interval` VARCHAR(10) COMMENT '时间周期', 
	max_position FLOAT COMMENT '最大持仓', 
	created_at DATETIME COMMENT '创建时间', 
	updated_at DATETIME COMMENT '更新时间', 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;
